freebsd_instance:
  image: freebsd-11-2-release-amd64

iocage_tests_task:
  create_pool_script:
    - truncate -s 20G /root/poolfile
    - zpool create pool /root/poolfile
  install_pkgs_script: pkg install -y git python3
  configure_python_script:
    - python3 -m ensurepip
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION && cat requirements.txt
    populate_script: python3 -m pip install -U pytest pytest-cov pytest-pep8 pytest-mock mock cython
  test_script: make install && pytest --zpool=pool
